GET http://localhost:3000/subscribers/

###

GET http://localhost:3000/subscribers/65a002457b21604e6a4be221

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name" : "Amazing",
    "subscribedToChannel": "lmao"
}

###
PATCH http://localhost:3000/subscribers/65a002457b21604e6a4be221
Content-Type: application/json

{
    "name" : "bruh"
}
