GET http://localhost:3000/posts/

###

GET http://localhost:3000/posts/65a50ecc31c2d8f4c158e3d8

###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "name" : "Jimin2",n
    "title": "bruh2d",
    "content": "huh2",
    "subscribedToChannel" : "computing scoiety"
}

###
PATCH http://localhost:3000/subscribers/65a002457b21604e6a4be221
Content-Type: application/json

{
    "name" : "bruh"
}
